[project]
name = "whats-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "alexandershov", email = "codumentary.com@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "uvicorn>=0.52.4",
]

[project.scripts]
whats-new = "whats_new:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
asyncio_mode = "auto"
