run:
	zig run src/main.zig src/stb_image.c -I src -framework OpenGL `pkg-config --libs sdl2` -- ./src/sharpen_fragment_shader.glsl ./src/barbara.jpg ./src/textured_quad_vertex_shader.glsl ./src/textured_quad_fragment_shader.glsl false false false

