      DIMENSION ICOSTS(1000, 1000), IROW(1000), IPREV(1000)
10    FORMAT (I4/(I4))
      READ 10,NROWS,NCOLS,((ICOSTS(I,J), J = 1,NCOLS),I=1,NROWS)
      DO 15 J=1,NCOLS
      IPREV(J) = ICOSTS(1,J)
15    IROW(J) = 0
      DO 50 I=2,NROWS
      IBEFOR=0
      DO 30 J = 1,NCOLS
      IBEFOR = MAX(IBEFOR, IPREV(J) + J)
30    IROW(J)=MAX(ICOSTS(I,J)+IBEFOR-J, IROW(J))
      IAFTER = 0
      DO 40 J = 1,NCOLS
      JR = NCOLS - J + 1
      IAFTER = MAX(IAFTER, IPREV(JR) - JR)
40    IROW(JR)=MAX(ICOSTS(I,JR) + IAFTER + JR, IROW(JR))
      DO  45 J = 1, NCOLS
      IPREV(J) = IROW(J)
45    IROW(J) = 0
50    CONTINUE
60    FORMAT (I8)
      IRES = 0
      DO 70 J=1,NCOLS
70    IRES = MAX(IRES, IPREV(J))
      PRINT 60, (IRES)
      END
