/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.demo

class App {
    val greeting: String
        get() {
            return "Testing!"
        }
}

fun main() {
    println(App().greeting)
}
