whats-my-age-again:
	uv run src/sound/midi_format.py  \
	 --notes 'B3 F#4 A#4 F#4 F#3 F#4 A#4 F#4 C#3 F#4 A#4 F#4 D#3 F#4 A#4 F#4 B3 F#4 A#4 F#4 F#3 F#4 A#4 F#4 C#3 F#4 A#4 F#4 D#3 F#4 A#4 F#4 B3 F#4 A#4 F#4 F#3 F#4 A#4 F#4 C#3 F#4 A#4 F#4 D#3 F#4 A#4 F#4 B3 F#4 A#4 F#4 F#3 F#4 A#4 F#4 C#3 F#4 A#4 F#4 D#3 F#4 A#4 F#4' \
	 --note-ticks 36 \
	 --output whats-my-age-again.mid
