[project]
name = "sound"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "alexandershov", email = "codumentary.com@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "python-rtmidi>=1.5.8",
]

[project.scripts]
sound = "sound:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
